# Generated by Django 3.0.5 on 2020-05-02 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_burguer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='burguer',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='burguer',
            old_name='image',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='burguer',
            old_name='ingredients',
            new_name='ingredientes',
        ),
        migrations.RenameField(
            model_name='burguer',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='burguer',
            old_name='price',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='name',
            new_name='nombre',
        ),
    ]
