# Generated by Django 3.0.5 on 2020-05-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_burguer', '0002_auto_20200502_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burguer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='burguer',
            name='ingredientes',
            field=models.ManyToManyField(blank=True, to='api_burguer.Ingredient'),
        ),
    ]
